name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - rewrite
  pull_request:
    branches: 
      - rewrite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-node@v2"
      with:
        node-version: "16"

    - name: Bob the Builder 🧔🔧
      run: |
        npm ci
        npm run build
