on:
  pull_request:
    branches:
    - "rewrite"
jobs:
  work:
    name: "work work 🍔"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-node@v2"
      with:
        node-version: "14"
    - run: npm ci
